<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGmosejp\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGmosejp/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGmosejp.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGmosejp\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \ContainerGmosejp\EccubeDevDebugProjectContainer([
    'container.build_hash' => 'Gmosejp',
    'container.build_id' => '1c1628a1',
    'container.build_time' => 1624268114,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGmosejp');
